# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['-municipio'],
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('CR', 'Criminal'), ('MU', 'Municipal'), ('MA', 'Medio Ambiente'), ('DH', 'Derechos Humanos'), ('NG', 'Ninguno')], default='CR', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='correo',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.Institucion'),
        ),
        migrations.AddField(
            model_name='correo',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizaciones.Municipio'),
        ),
    ]
