# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institucion', '0001_initial'),
        ('localizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=55)),
                ('apellidos', models.CharField(max_length=55)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('ultima_conexion', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_res', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('institucion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institucion.Institucion')),
                ('zona', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='localizaciones.Direccion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
